; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

; Velocidad del monitor serial (Estándar para ESP32)
monitor_speed = 115200

; Filtros para que el log se vea limpio y con colores
monitor_filters = direct, esp32_exception_decoder

; Opcional: Si tienes problemas de puerto, descomenta y pon tu puerto COM
; upload_port = COM3